Add Collaborations model
Distilled-Platform/api.getdistilled.io pull request #65
Opened 2023-04-28 22:01 UTC by jdbohrman

2023-04-30 16:25 UTC, StephenForrest requested changes
A few things but overall looks good! Remember BEFORE changing the migration file to `rails db:rollback` to undo the migration before changing it and re-`db:migrate`-ing forwards to change the schema

2023-04-30 16:25 UTC, StephenForrest commented on app/models/collaboration.rb
> +	validates :relationship_type, presence: true
Spacing here is off, should just be 2 spaces/tab

2023-04-30 16:25 UTC, StephenForrest commented on db/migrate/20230428215747_create_collaborations.rb
> +      t.string :stakeholder_type
It's best to add these as references (as it also indexes them):

```suggestion
      t.references :stakeholder, polymorphic: true
```

2023-04-30 16:25 UTC, StephenForrest commented on db/migrate/20230428215747_create_collaborations.rb
> +      t.string :subject_type
Same here
```suggestion
      t.references :subject, polymorphic: true
```

2023-04-30 16:25 UTC, StephenForrest commented on app/models/collaboration.rb
> +
Somewhere here you want to define the `enum` too:

```suggestion
  enum relationship_type: { stakeholder: 0, owner: 1 }
```

2023-05-01 06:01 UTC, jdbohrman commented
> A few things but overall looks good! Remember BEFORE changing the migration file to `rails db:rollback` to undo the migration before changing it and re-`db:migrate`-ing forwards to change the schema

Should be good to merge now 💪

2023-05-01 18:46 UTC, StephenForrest commented on app/models/collaboration.rb
> +	validates :relationship_type, presence: true
Just this spacing but now everything else looks great!

2023-05-01 19:47 UTC, StephenForrest approved these changes

2023-05-01 19:47 UTC, merged